apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- manifests.yaml

patchesStrategicMerge:
- manifests_label_patch.yaml

configurations:
- kustomizeconfig.yaml
