
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /default-mutate-vmoperator-vmware-com-v1alpha1-virtualmachine
  failurePolicy: Fail
  name: default.mutating.virtualmachine.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha1-virtualmachine
  failurePolicy: Fail
  name: default.validating.virtualmachine.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha1-virtualmachineclass
  failurePolicy: Fail
  name: default.validating.virtualmachineclass.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachineclasses
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha1-virtualmachineservice
  failurePolicy: Fail
  name: default.validating.virtualmachineservice.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachineservices
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha1-virtualmachinesetresourcepolicy
  failurePolicy: Fail
  name: default.validating.virtualmachinesetresourcepolicy.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinesetresourcepolicies
