---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-mutate-vmoperator-vmware-com-v1alpha5-virtualmachine
  failurePolicy: Fail
  name: default.mutating.virtualmachine.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-mutate-vmoperator-vmware-com-v1alpha5-virtualmachinegroup
  failurePolicy: Fail
  name: default.mutating.virtualmachinegroup.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinegroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-mutate-vmoperator-vmware-com-v1alpha5-virtualmachinereplicaset
  failurePolicy: Fail
  name: default.mutating.virtualmachinereplicaset.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinereplicasets
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate--v1-persistentvolumeclaim
  failurePolicy: Fail
  name: default.validating.persistentvolumeclaim.vmoperator.vmware.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - persistentvolumeclaims
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachine
  failurePolicy: Fail
  name: default.validating.virtualmachine.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachines
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachineclass
  failurePolicy: Fail
  name: default.validating.virtualmachineclass.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachineclasses
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachinegroup
  failurePolicy: Fail
  name: default.validating.virtualmachinegroup.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinegroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachinepublishrequest
  failurePolicy: Fail
  name: default.validating.virtualmachinepublishrequest.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinepublishrequests
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachinereplicaset
  failurePolicy: Fail
  name: default.validating.virtualmachinereplicaset.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinereplicasets
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachineservice
  failurePolicy: Fail
  name: default.validating.virtualmachineservice.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachineservices
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachinesetresourcepolicy
  failurePolicy: Fail
  name: default.validating.virtualmachinesetresourcepolicy.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinesetresourcepolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachinesnapshot
  failurePolicy: Fail
  name: default.validating.virtualmachinesnapshot.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinesnapshots
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha1-webconsolerequest
  failurePolicy: Fail
  name: default.validating.webconsolerequest.v1alpha1.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - webconsolerequests
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /default-validate-vmoperator-vmware-com-v1alpha5-virtualmachinewebconsolerequest
  failurePolicy: Fail
  name: default.validating.virtualmachinewebconsolerequest.v1alpha5.vmoperator.vmware.com
  rules:
  - apiGroups:
    - vmoperator.vmware.com
    apiVersions:
    - v1alpha5
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualmachinewebconsolerequests
  sideEffects: None
