- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: KUBERNETES_SERVICE_HOST
    value: "127.0.0.1"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: KUBERNETES_SERVICE_PORT
    value: "6443"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: VSPHERE_NETWORKING
    value: "<VSPHERE_NETWORKING_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_INSTANCE_STORAGE
    value: "<FSS_WCP_INSTANCE_STORAGE_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: NETWORK_PROVIDER
    value: "<NETWORK_PROVIDER_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_ISO_SUPPORT
    value: "<FSS_WCP_VMSERVICE_ISO_SUPPORT_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: PRIVILEGED_USERS
    value: "<COMMA_SEPARATED_LIST_OF_USERS>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_PODVMONSTRETCHEDSUPERVISOR
    value: "<FSS_PODVMONSTRETCHEDSUPERVISOR>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_TKG_Multiple_CL
    value: "<FSS_WCP_TKG_Multiple_CL_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_K8S_WORKLOAD_MGMT_API
    value: "<FSS_WCP_VMSERVICE_K8S_WORKLOAD_MGMT_API_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_RESIZE
    value: "<FSS_WCP_VMSERVICE_RESIZE_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_RESIZE_CPU_MEMORY
    value: "<FSS_WCP_VMSERVICE_RESIZE_CPU_MEMORY_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET
    value: "<FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_WORKLOAD_DOMAIN_ISOLATION
    value: "<FSS_WCP_WORKLOAD_DOMAIN_ISOLATION_VALUE>"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_INCREMENTAL_RESTORE
    value: "<FSS_WCP_VMSERVICE_INCREMENTAL_RESTORE_VALUE>"
#
# Feature state switch flags beneath this line are enabled on main and only
# retained in this file because it is used by internal testing to determine the
# state of the feature. Since this is used by older branches as well, the flags
# must remain, otherwise the absence of the flag indicates a feature is not
# present or disabled.
#

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_BACKUPRESTORE
    value: "true"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_Unified_TKG
    value: "true"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VMSERVICE_V1ALPHA2
    value: "true"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VM_CLASS_AS_CONFIG
    value: "true"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VM_CLASS_AS_CONFIG_DAYNDATE
    value: "true"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_VM_IMAGE_REGISTRY
    value: "true"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_NAMESPACED_VM_CLASS
    value: "true"

- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: FSS_WCP_WINDOWS_SYSPREP
    value: "true"
