apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: certman-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certman-role
subjects:
- kind: ServiceAccount
  name: vmoperator-service-account
  namespace: system
