---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - resourcequotas
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfiguration
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cns.vmware.com
  resources:
  - cnsnodevmattachments
  - storagepolicyusages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cns.vmware.com
  resources:
  - cnsnodevmattachments/status
  verbs:
  - get
  - list
- apiGroups:
  - cns.vmware.com
  resources:
  - storagepolicyquotas
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cns.vmware.com
  resources:
  - storagepolicyquotas/status
  - storagepolicyusages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.nsx.vmware.com
  resources:
  - subnetports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.nsx.vmware.com
  resources:
  - subnetports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iaas.vmware.com
  resources:
  - capabilities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iaas.vmware.com
  resources:
  - capabilities/status
  verbs:
  - get
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - clustercontentlibraryitems
  - contentlibraryitems
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - clustercontentlibraryitems/status
  - contentlibraries/status
  - contentlibraryitems/status
  verbs:
  - get
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - contentlibraries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netoperator.vmware.com
  resources:
  - networkinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.tanzu.vmware.com
  resources:
  - availabilityzones
  - availabilityzones/status
  - zones/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.tanzu.vmware.com
  resources:
  - zones
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - clustervirtualmachineimages
  - virtualmachineclasses
  - virtualmachineimages
  - virtualmachinepublishrequests
  - virtualmachines
  - virtualmachineservices
  - virtualmachinesetresourcepolicies
  - virtualmachinewebconsolerequests
  - webconsolerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - clustervirtualmachineimages/status
  - virtualmachineimages/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineclasses/status
  - virtualmachinepublishrequests/status
  - virtualmachinereplicasets/status
  - virtualmachines/status
  - virtualmachineservices/status
  - virtualmachinesetresourcepolicies/status
  - virtualmachinewebconsolerequests/status
  - webconsolerequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinereplicasets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmware.com
  resources:
  - virtualnetworkinterfaces
  - virtualnetworkinterfaces/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
