
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cns.vmware.com
  resources:
  - cnsnodevmattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cns.vmware.com
  resources:
  - cnsnodevmattachments/status
  verbs:
  - get
  - list
- apiGroups:
  - netoperator.vmware.com
  resources:
  - networkinterfaces
  - vmxnet3networkinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.tanzu.vmware.com
  resources:
  - availabilityzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.tanzu.vmware.com
  resources:
  - availabilityzones/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentlibraryproviders
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentlibraryproviders/status
  verbs:
  - get
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentsourcebindings
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - contentsources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachine
  verbs:
  - get
  - list
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachine/status
  verbs:
  - get
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineclassbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineimages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinesetresourcepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinesetresourcepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmware.com
  resources:
  - virtualnetworkinterfaces
  - virtualnetworkinterfaces/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
