---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cns.vmware.com
  resources:
  - cnsnodevmattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cns.vmware.com
  resources:
  - cnsnodevmattachments/status
  verbs:
  - get
  - list
- apiGroups:
  - cns.vmware.com
  resources:
  - storagepolicyquotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - clustercontentlibraryitems
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - clustercontentlibraryitems/status
  verbs:
  - get
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - contentlibraries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - contentlibraries/status
  verbs:
  - get
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - contentlibraryitems
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imageregistry.vmware.com
  resources:
  - contentlibraryitems/status
  verbs:
  - get
- apiGroups:
  - netoperator.vmware.com
  resources:
  - networkinterfaces
  - vmxnet3networkinterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nsx.vmware.com
  resources:
  - subnetports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nsx.vmware.com
  resources:
  - subnetports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.tanzu.vmware.com
  resources:
  - availabilityzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - topology.tanzu.vmware.com
  resources:
  - availabilityzones/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - clustervirtualmachineimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - clustervirtualmachineimages/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineimages/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinepublishrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinepublishrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachineservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinesetresourcepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinesetresourcepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinewebconsolerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - virtualmachinewebconsolerequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - webconsolerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vmoperator.vmware.com
  resources:
  - webconsolerequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vmware.com
  resources:
  - virtualnetworkinterfaces
  - virtualnetworkinterfaces/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
