apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachineClass
metadata:
  name: guaranteed-xsmall
spec:
  hardware:
    cpus: 2
    memory: 2Gi
  policies:
    resources:
      requests:
        cpu: 2
        memory: 2Gi
      limits:
        cpu: 2
        memory: 2Gi
