---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: clustercontentlibraryitems.imageregistry.vmware.com
spec:
  group: imageregistry.vmware.com
  names:
    kind: ClusterContentLibraryItem
    listKind: ClusterContentLibraryItemList
    plural: clustercontentlibraryitems
    shortNames:
    - cclitem
    singular: clustercontentlibraryitem
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.name
      name: vSphereName
      type: string
    - jsonPath: .status.clusterContentLibraryRef
      name: ClusterContentLibraryRef
      type: string
    - jsonPath: .status.type
      name: Type
      type: string
    - jsonPath: .status.ready
      name: Ready
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterContentLibraryItem is the schema for the content library
          item API at the cluster scope. Currently, ClusterContentLibraryItem are
          immutable to end users.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterContentLibraryItemSpec defines the desired state of
              a ClusterContentLibraryItem.
            properties:
              uuid:
                description: UUID is the identifier which uniquely identifies the
                  library item in vCenter. This field is immutable.
                type: string
            required:
            - uuid
            type: object
          status:
            description: ClusterContentLibraryItemStatus defines the observed state
              of ClusterContentLibraryItem.
            properties:
              cached:
                default: false
                description: Cached indicates if the library item files are on disk
                  in vCenter.
                type: boolean
              certificateVerificationInfo:
                description: CertificateVerificationInfo shows the certificate verification
                  status and the signing certificate.
                properties:
                  certChain:
                    description: CertChain shows the signing certificate in base64
                      encoding if the library item is signed.
                    items:
                      type: string
                    type: array
                  status:
                    description: Status shows the certificate verification status
                      of the library item.
                    type: string
                required:
                - status
                type: object
              clusterContentLibraryRef:
                description: ClusterContentLibraryRef is the name of the ClusterContentLibrary
                  resource that this item belongs to.
                type: string
              conditions:
                description: Conditions describes the current condition information
                  of the ClusterContentLibraryItem.
                items:
                  description: Condition defines an observation of an Image Registry
                    Operator API resource operational state.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.
                        If that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    severity:
                      description: Severity provides an explicit classification of
                        Reason code, so the users or machines can immediately understand
                        the current situation and act accordingly. The Severity field
                        MUST be set only when Status=False.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              contentVersion:
                description: ContentVersion indicates the version of the library item
                  content. This value is incremented when the files comprising the
                  content library item are changed in vCenter.
                type: string
              creationTime:
                description: CreationTime indicates the date and time when this library
                  item was created.
                type: string
              description:
                description: Description is a human-readable description for this
                  library item.
                type: string
              lastModifiedTime:
                description: LastModifiedTime indicates the date and time when this
                  library item was last updated. This field is updated when the library
                  item properties are changed or the file content is changed.
                type: string
              lastSyncTime:
                description: LastSyncTime indicates the date and time when this library
                  item was last synchronized. This field applies only to subscribed
                  library items.
                type: string
              metadataVersion:
                description: MetadataVersion indicates the version of the library
                  item metadata. This value is incremented when the library item properties
                  such as name or description are changed in vCenter.
                type: string
              name:
                description: ItemName specifies the name of the content library item
                  in vCenter.
                type: string
              ready:
                default: false
                description: Ready denotes that the library item is ready to be used.
                type: boolean
              securityCompliance:
                description: SecurityCompliance shows the security compliance of the
                  library item.
                type: boolean
              size:
                description: Size indicates the library item size in bytes
                format: int32
                type: integer
              type:
                description: Type string indicates the type of the library item in
                  vCenter. Possible types are "Ovf" and "Iso".
                type: string
            required:
            - cached
            - clusterContentLibraryRef
            - contentVersion
            - creationTime
            - lastModifiedTime
            - metadataVersion
            - name
            - ready
            - type
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
